apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::870653356349:role/UdacityFlaskDeployCBKubectlRole
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::870653356349:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-21T14:32:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "6307"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2df03fbd-5cec-42b5-98a3-74eab37e3165
